config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  :help,    to: "static_pages#help"
  get  :about,   to: "static_pages#about"
  get  :contact, to: "static_pages#contact"
  get  :search,  controller: :main
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :following, :followers, only: [:index]
    collection {post :import}
  end
  resources :microposts, only: [:index, :create, :edit, :update, :destroy] do
    resource :like, only: [:create, :destroy], module: :microposts
  end
  resources :relationships, only: [:create, :destroy]
  resources :comments
  resources :exports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: %i(edit update destroy)
  before_action :authenticate_user!, only: :create
  before_action :correct_user, only: %i(edit update destroy)

  def edit
    @micropost = @comment.micropost
    respond_to do |format|
      format.html
      format.js
    end  
  end

  def create
    @comment = current_user.comments.build comment_params
    @micropost = @comment.micropost
    if @comment.save
      respond_to do |format|
        format.html {redirect_to request.referrer}
        format.js
      end
    else
      flash[:danger] = t ".failed"
      redirect_to request.referrer
    end
  end

  def update
    @micropost = @comment.micropost
    if @comment.update_attributes comment_params
      respond_to do |format|
        format.html {redirect_to request.referrer}
        format.js
      end
    else
      redirect_to request.referrer
    end
  end

  def destroy
    @micropost = @comment.micropost
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
  end

  private

  def find_comment
    @comment = Comment.find_by id: params[:id]
  end

  def comment_params
    params.require(:comment).permit :content, :micropost_id
  end

  def correct_user
    @comment = Comment.find_by id: params[:id]
    unless (@comment.user == current_user) || current_user.admin?
      redirect_to request.referrer
    end
  end
end

app/views/comments/_comment.html.erb
<li class="list-group-item" id="comment-<%= comment.id %>">
  <span>
    <%= link_to gravatar_for(comment.user, size: 30), comment.user %>
    <%= link_to comment.user.name, comment.user %></br>
    <%= comment.content %>
  </span>
  <div class='timestamp'>
    <%= time_ago_in_words(comment.created_at) %> ago
    <% if current_user? comment.user %>
      <%= link_to t(".edit"), edit_comment_path(comment), remote: true %>
        <span id="myModal"></span>
      <%#= link_to "Edit", "#editForm#{comment.id}",
            data: {toggle: 'collapse'},
            aria: {expanded: 'false', controls: "#editForm#{comment.id}"} %>
      <%= link_to t(".delete"), comment, remote: true, method: :delete, data: {confirm: t(".confirm")}%>
        <!--<div class='collapse' id=<%="editForm#{comment.id}"%>>
          <%= render 'comments/form', comment: comment, micropost: comment.micropost %>
        </div>-->
    <% elsif user_signed_in? && current_user.admin? || current_user?(comment.micropost.user) %>
      <%= link_to t(".delete"), comment, remote: true, method: :delete, data: {confirm: t(".confirm")}%>
    <% end %>
  </div>
</li>

app/views/comments/_form.html.erb
<%= form_for comment, remote: true do |f| %>
  <div class="field">
    <%= f.hidden_field :micropost_id, value: "#{micropost.id}" %>

    <%= f.text_field :content, placeholder: t(".placeholder") %>
    <%= f.submit t(".submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/_modal.html.erb
<div class="modal fade" id="form_modal" role="modal" data-backdrop="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-center"><%= t ".edit" %></h4>
      </div>
      <div class="modal-body">
        <%= render "comments/form", comment: comment, micropost: micropost %>
      </div>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$("#micropost-<%= @micropost.id %> .list-group").append("<%= escape_javascript(render('comments/comment', comment: @comment)) %>");
$("#new_comment #comment_content").val("");
$("#micropost-<%= @micropost.id %> #comments").html("<%= pluralize(@micropost.comments.count, "Comment") %>");

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();
$('#comments').html("<%= pluralize(@micropost.comments.count, "Comment") %>");

app/views/comments/edit.js.erb
$('#myModal').html('<%= escape_javascript(render('modal', comment: @comment, micropost: @micropost)) %>');
$('#form_modal').modal('show');
$("body").removeClass("modal-open");

app/views/comments/update.js.erb
var comment_content = '<%= escape_javascript(render('comments/comment', comment: @comment)) %>';
$('#comment-<%= @comment.id %>').html($(comment_content).html());
$('#editForm<%= @comment.id %>').collapse('hide')