config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  :help,    to: "static_pages#help"
  get  :about,   to: "static_pages#about"
  get  :contact, to: "static_pages#contact"
  get  :search,  controller: :main
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :following, :followers, only: [:index]
    collection {post :import}
  end
  resources :microposts, only: [:index, :create, :edit, :update, :destroy] do
    resource :like, only: [:create, :destroy], module: :microposts
  end
  resources :relationships, only: [:create, :destroy]
  resources :comments
  resources :exports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 60}
  validates :content, presence: true
  mount_uploader :picture, PictureUploader
  validate  :picture_size

  default_scope -> {order(created_at: :desc)}
  
  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/microposts/likes_controller.rb
class Microposts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_micropost

  def create
    @like = @micropost.likes.find_or_initialize_by user_id: current_user.id
    if @like.save
      respond_to do |format|
        format.html {redirect_to request.referrer}
        format.js
      end
    else
      flash[:danger] = t ".failed"
      redirect_to request.referrer
    end
  end

  def destroy
    @micropost.likes.find_by(user_id: current_user.id).destroy
    respond_to do |format|
      format.html {redirect_to request.referrer}
      format.js
    end
  end

  private

  def like_params
    params.require(:comment).permit :micropost_id
  end

  def find_micropost
    @micropost = Micropost.find_by id: params[:micropost_id]
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def index
    @microposts = Micropost.all
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = t ".success"
      redirect_to root_url
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def update
    if @micropost.update_attributes micropost_params
      flash[:success] = t ".updated_success"
      redirect_to request.referrer
    else
      render :edit
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = t ".post_deleted"
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:title, :content, :picture)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end

end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to image_tag(@user.avatar.url, size: "40x40", crop: :fill), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <div class="title"><%= micropost.title %></div>
  <div>
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </div>
  <span>
    <%= t ".posted", time: time_ago_in_words(micropost.created_at) %>
    <% if current_user? micropost.user %>
      <%= link_to t(".edit"), edit_micropost_path(micropost) %>
      <%= link_to t(".delete"), micropost, method: :delete, data:{confirm: t(".confirm")} %>
    <% end %>
  </span>
  <div id="likes">
    <%= pluralize(micropost.likes.count, "like") %>
  </div>
  <% if user_signed_in? %>
    <div class="like_or_unlike">
      <%= render "microposts/likes/button", micropost: micropost %>
    </div>
    <div class="list-group-item">
      <%= render "comments/form", comment: Comment.new, micropost: micropost %>
    </div>
  <% end %>
  <h4 id="comments">
    <%= pluralize(micropost.comments.count, "Comment") %>
  </h4>
  <ul class="list-group">
    <%= render micropost.comments %>
  </ul>
</li>

app/views/microposts/edit.html.erb
<% provide :title, t(".edit") %>

<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="picture">
    <%= image_tag @micropost.picture.url if @micropost.picture? %>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </div>
  <%= f.submit t(".edit"), class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>