config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  :help,    to: "static_pages#help"
  get  :about,   to: "static_pages#about"
  get  :contact, to: "static_pages#contact"
  get  :search,  controller: :main
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :following, :followers, only: [:index]
    collection {post :import}
  end
  resources :microposts, only: [:index, :create, :edit, :update, :destroy] do
    resource :like, only: [:create, :destroy], module: :microposts
  end
  resources :relationships, only: [:create, :destroy]
  resources :comments
  resources :exports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t(".writer", url1: "http://www.railstutorial.org/", url2: "http://www.michaelhartl.com/").html_safe %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".help"), help_path %></li>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
      <li><%= t(".news", url: "http://news.railstutorial.org/").html_safe %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".home"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= form_with url: search_path, local: true, method: :get, class: "form-inline" do |form| %>
              <div class="form-group">
                <%= form.text_field :q, placeholder: "Search user", data: {behavior: "autocomplete"}, class: "form-control" %>
              </div>
              <%= form.button "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
            <% end %>
          </li>
          <li><%= link_to t(".users"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t ".account" %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".log_in"), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>